FROM mcr.microsoft.com/dotnet/framework/sdk:5.0 AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.csproj .
RUN JSONAPI restore

# copy and build everything else
COPY . .
WORKDIR /app
RUN JSONAPI publish -c Release -o out --no-restore


FROM mcr.microsoft.com/dotnet/framework/runtime:4.8 AS runtime
WORKDIR /app
COPY --from=build /app/out ./
ENTRYPOINT ["dotnetapp.exe"]
